 platform :ios, '13.0'

target 'Skatable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skatable
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  pod 'SwiftGen'
  pod 'SnapKit', :inhibit_warnings => true

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
            config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
        end
    end
end
