name: Skatable

settings:
  DEVELOPMENT_TEAM: H7BM7N56V5
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true

options:
  bundleIdPrefix: com.vcoutasso

targets:
  Skatable:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    settings:
      TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: Skatable
    preBuildScripts:
      - name: SwiftLint
        script: |
          "${PODS_ROOT}/SwiftLint/swiftlint" --config ../config/swiftlint.yml
      - name: SwiftGen
        script: |
          "${PODS_ROOT}/SwiftGen/bin/swiftgen" config run --config ../config/swiftgen.yml
