input_dir: ../App/Skatable/Resources/
output_dir: ../App/Skatable/Resources/Generated/
strings:
  inputs: 
    - Base.lproj
    - Names.strings
  filter: .+\.strings$
  outputs:
    - templateName: structured-swift5
      output: Strings.swift
      params:
          enumName: Strings
xcassets:
  inputs: Assets.xcassets
  outputs:
    - templateName: swift5
      output: Assets.swift
      params:
          enumName: Assets
fonts:
  inputs: Fonts
  outputs:
    - templateName: swift5
      output: Fonts.swift
      params:
          enumName: Fonts
