name: Build

on: 
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macos-11.0
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app && /usr/bin/xcodebuild -version

      - name: Install xcodegen
        run: brew install xcodegen

      - name: Generate project and install dependencies
        run: make generate

      - name: Build project
        run: xcodebuild -workspace App/Royals.xcworkspace -scheme Royals -destination platform\=iOS\ Simulator,OS\=14.5,name\=iPhone\ 12 build | xcpretty && exit ${PIPESTATUS[0]}
